### ISSUE TITLE
Possible to translate string and pass as prop?

### ISSUE THREAD

**Issue by lochstar** [CherrySoftware/react-translate-maker#2]
Hi,

I was wondering how you would go about passing a translated string to a placeholder attribute on an input.

I could use translate-maker to get the translated string and pass it as a prop. Is it possible to do this without requiring translate-maker in my project?

Thanks

**Comment by seeden** [comment]
I have updated documentation. Please take a look on:
https://github.com/CherrySoftware/react-translate-maker#placeholder-and-direct-translations

**Comment by lochstar** [comment]
Thanks!
